
services:
  postgres:
    image: postgres:18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata     
    container_name: postgres-db
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
      - ./data/postgres-data:/var/lib/postgresql/data/pgdata
